trunk/config/routes.rb
Adhub::Application.routes.draw do
  resources :ad_requests do
    post :shown, :clicked, :on=>:member
  end

  resources :parties do
    get :autocomplete_search, :on=>:collection
    post :archived, :on=>:member
  end

  resources :contracts do
    post :stop, :on=>:member
    put :renewal, :on=>:member
  end
  
  match '/members/my_account',:controller=>'members',:action=>'edit',:format=>:html

  resources :members do 
    get 'active', :on=>:member
    get 'check_email', 'forget_password_form', :on=>:collection
    post :resend_active_email, :on=>:collection
    post :forget_password_form,:on=>:collection
    get :modify_passwd,:on=>:collection
    post :update_passwd,:on=>:member
    post :supplement,:on=>:member
    get :faces,:on=>:member 
  end
  
  namespace :admin do
    resources :parties do
      post :save_account,:on=>:member
      resources :contracts
    end

    resources :contracts do
      put :renewal, :on=>:member
      post :stop, :on=>:member
    end
    resources :members do
      member do
        post :locked_Or_unlocked
        post :supplement
        get :show_records     
        get :faces
      end     
      get :autocomplete_search, :on=>:collection
    end

    resources :advertisements do
      post :approve, :on=>:member
    end
    
    resources :ad_containers do
      post :approve, :on=>:member     
    end
    
    resources :account_transactions

    resources :cash_claims
    
    resources :content_categories
    
    resources :sdks do
      get :next_step,:on=>:member
      post :upload_sdk,:on=>:member
    end
    match '/', :controller=>'members', :action=>'index'
  end

  namespace :my_company do
    resources :parties do
      get :show_account_transactions,:on=>:collection
    end
    resources :members do
      post :lock, :on=>:collection
      post :unlock, :on=>:collection
      post :reset_passwd, :on=>:collection
    end
  end
  
  namespace :ad_owner do
    resources :campaigns do
      post 'stop', 'execute', 'submit', 'set_budget', :on=>:member
      get 'budgets', :on=>:collection
      get 'budget', :on=>:member
      resources :publish_policies do
        post 'stop',:on=>:member
        post 'execute',:on=>:member
      end
    end
    
    match '/', :controller=>'console', :action=>'index'
    match '/console/select_ad_owner', :controller=>'console', :action=>'select_ad_owner'
    match '/ad_resources/:ad_format/:action(.:format)', :controller=>'ad_resources'

    resources :ad_resources
    
    resources :advertisements do
      post :submit_approve,:on=>:member
      post :revoke, :on=>:member
      post :stop, :on=>:member
      post :execute,:on=>:member
      
      resources :publish_policies do
         get :step_2,:on=>:member
         get :step_3,:on=>:member
         get :search,:on=>:member
         get :judge_successful_step_2,:on=>:member
         get :select_content_categories,:on=>:member
         post :stop,:on=>:member
         post :execute,:on=>:member
         post :decrease_ad_container,:on=>:member
         post :increase_ad_container,:on=>:member
         post :notice_to_price,:on=>:member
         post :save_step_3,:on=>:member
         post :save_content_categories,:on=>:member
      end
    end

    resource :report do
      get 'summary', 'daily', :on=>:member
    end
  end

  namespace :agent do
    match '/', :controller=>'console', :action=>:index
  end

  namespace :publisher do
    resources :black_lists
    resources :prices
    resources :publish_policies do
      get :ad_detail, :on=>:collection
    end

    resources :ad_containers do
       post :submission,:on=>:member
       get :show_identity,:on=>:member
    end

    resource :report do 
      get 'summary', 'daily', :on=>:member
    end
     
    resources :bank_accounts do 
       get :show_ex ,:on=>:collection 
       post :send_dynamic_pass ,:on=>:collection 
    end
    
    resources :cash_claims

    match '/', :controller=>'console', :action=>:index
  end

  namespace :member do
    resource :cash_claims
  end
  
  scope '/target/:target_type/:target_id'  do
    resources :approve_logs
  end
  
  resources :sdks do
    collection do
      get :sdks_list
    end
  end
  match 'sdks/:os_type/download',:controller=>'sdks',:action=>'download'
  
  resource :session 
  

  match '/', :controller=>'sites', :action=>'index', :as=>'main'
  match '/static/:action', :controller=>'sites'
  
  

end

trunk/app/controllers/admin/members_controller.rb
# -*- coding: utf-8 -*-
require 'dynamic_query'

class Admin::MembersController < Admin::AdminController
    
    include Imon::DynamicQuery
    
    def index
      exps = expressions_from_params params,Member
      @members = Member.paginate :all,:conditions=>self.and(exps).conditions,:order=>'email',:page=>params[:page],:per_page=>10
    end
    
    def show
       @member = Member.find params[:id] 
       if @member
          @account_transactions = AccountTransaction.find :all,:conditions=>['account_id =? and operation =?',@member.id,0],:order=>"created_at desc",:limit=>10
       end
    end
    
    def locked_Or_unlocked
         @member = Member.find params[:id]
         if @member.status != Member::STATUS_LOCKED
              @member.update_attribute (:status,Member::STATUS_LOCKED)
         else
              @member.update_attribute (:status,Member::STATUS_ACTIVE)      
         end 
         @member.reload               
    end
    
    def show_records
        @member = Member.find params[:id]
        if @member
          @account_transactions = AccountTransaction.paginate :all,:conditions=>['account_id =? and operation =?',@member.party.account.id,0],:order=>"created_at desc",
                                  :page =>params[:page],:per_page => 10
        end
    end
    
    def faces
       @member = Member.find params[:id]
    end
    
    def supplement
       @member = Member.find params[:id]
       if  @member
           @account_transaction = AccountTransaction.new
           @account_transaction.account_id = @member.paryt.account.id if @member.party.account
           @account_transaction.operator_id = current_user.id
           @account_transaction.op_way = params[:op_way].to_i
           @account_transaction.amount = params[:amount].to_f

           unless @account_transaction.save
                     flash.now[:notice]= '操作不成功'
                     render :nothing=>true
           else
                        @account_transation.reload
                        @member.party.account.balance += @account_transaction.amount
                        @member.party.save!
                        MemberMailer.account_transaction_note(@member,@account_transaction).deliver
                        flash[:notice] = '操作成功'
                        redirect_to :action => :show          
           end
       end
      
    end
    
  def autocomplete_search
    kw = "%#{params[:term]}%"
    members = Member.find :all, :conditions=>['name like ? or email like ?', kw, kw]
    return_v=[]
    unless members.nil? or members.count==0
        members.each do |member|
        return_v << member.label
        end
    end
    render :json=>return_v
  end

    protected
    def expression_for_name(name)
      self.like :real_name,name      
    end
    
    def expression_for_is_admin(is_admin)
      self.equal (:is_admin,is_admin)
    end
         
    def expression_for_status(status)
       self.equal(:status,status)
    end 
end

trunk/app/controllers/members_controller.rb
# -*- coding: utf-8 -*-
require 'dynamic_query'
require 'date'

class MembersController < ApplicationController
  include Imon::DynamicQuery
  layout 'default'
  select_main_menu 'mnu_my_account'

  def new
    @member = Member.new
  end

  def create
    @member = Member.new params[:member]
    @member.status = Member::STATUS_REGISTERED
    @member.generate_activation_code
    if @member.save
      MemberMailer.activation(@member).deliver
    else
      render :action=>:new
    end
  end
  
  def update
     @member = Member.find params[:id]
     unless @member.update_attributes params[:member]
       alert '编辑不成功！'
       render '/ad_owner'
     else
       render :update do |page|
        if params[:forward_to].nil? or params[:forward_to].empty?
         page.alert '编辑成功！'
        else
          page.redirect_to params[:forward_to]
        end
       end       
     end 
  end
  
  def edit
    @member = current_user
  end
  
  def active
    member = Member.find params[:id]
    if member.activation_code == params[:activation_code]
      member.active!
      flash[:notice] = "您的帐号已经激活，您现在可以正常登录了。"
      redirect_to new_session_url(:format=>:html)
    else
      flash[:notice] = "激活码不正确。"
      redirect_to '/'
    end    
  end
  
  def modify_passwd
    @member = current_user
  end
  
  def update_passwd
    @member = current_user
     if @member.password_hash == Imon::ActiveRecord::Password::encrypt(params[:passwd])
        if params[:new_passwd] == params[:confirm_passwd]
           unless @member.update_attribute(:password_hash,Imon::ActiveRecord::Password::encrypt(params[:new_passwd]))
             alert '修改密码不成功！'
           else
             render :update do |page|
               page.alert '修改密码成功！'
             end
             #render :nothing=>true
           end
        else
          alert '输入新密码不一致！'
        end
    else
      alert '原有密码不正确！'
    end
  end
  
  def faces
       @member = current_user
  end
    
    def supplement
       @member = current_user
       if  @member
           @account_transaction = AccountTransaction.new
           @account_transaction.member_id = @member.id
           @account_transaction.operator_id = current_user.id
           @account_transaction.op_way = params[:op_way].to_i
           @account_transaction.amount = params[:amount].to_f
           @account_transaction.balance = @member.account_balance + params[:amount].to_f
           # @account_transaction.reload
           unless @account_transaction.save
                     flash.now[:notice]= '操作不成功'
           else
                        @member.account_balance = @account_transaction.balance
                        @member.save!
                        flash[:notice] = '操作成功'
                        render :action => :edit          
           end
       end       
    end

  def check_email
    email = nil
    email = params[:member][:email] if params[:member]
    unless email.nil? or email.empty?
      cnt = Member.count :conditions=>['email = ? and id <> ? ', email, params[:id]] unless params[:id].nil? or params[:id].empty?
      cnt = Member.count :conditions=>['email = ? ', email ] if params[:id].nil? or params[:id].empty?
      render :text=>(cnt == 0), :layout=>false
    else
      render :text=>'true', :layout=>false
    end
  end
  
  def resend_active_email
    member = Member.find_by_email params[:email]
    if member
      unless MemberMailer.activation(member).deliver
          alert '邮件发送不成功！'
      else
         render :update do |page|
              page.alert '邮件发送成功！'
         end        
      end
    end
  end

  def forget_password_form
    member = Member.find_by_sql("select * from members m where email= '#{params[:email]}'").first
    if member.nil?
      alert '邮箱错误！请重新输入邮箱地址'
    else
      new_passwd = member.reset_passwd
      MemberMailer.send_password(member, new_passwd).deliver
      render :update do |page|
        page.alert '新密码已经发送到你注册邮箱！'
      end
    end
  end
end

trunk/app/controllers/my_company/members_controller.rb
# -*- coding: utf-8 -*-
require 'dynamic_query'
class MyCompany::MembersController < MyCompany::MyCompanyController
  include Imon::DynamicQuery
  layout "default"
  select_main_menu "mnu_my_company"
  before_filter :find_member, :only=>[:edit, :update, :lock, :unlock, :reset_passwd]
  require_privilege :manage_employee, :data_object=>:@party
  before_filter :check_privilege

  def index
    exps = []
    exps << self.like("members.email", params[:email]) if params[:email] and !params[:email].empty?
    exps << self.like("members.real_name", params[:real_name]) if params[:real_name] and !params[:real_name].empty?
    exps << self.exists("select * from members_roles mr where mr.member_id = members.id and mr.role_id = ?", params[:role_id] ) if params[:role_id] and !params[:role_id].empty?
    @members = current_user.party.members.paginate :conditions=>self.and(exps).conditions, :order=>"email", :page=>params[:page], :per_page=>15
  end # def index

  def create
    @member = Member.new params[:member]
    @member.party = current_user.party
    Member.transaction do 
      pwd = @member.new_passwd
      @member.password = pwd
      unless @member.save
        flash.now[:notice] = "员工帐号创建失败！"
        render :action=>:new
      else
        MemberMailer.company_activation(current_user.party, @member, pwd).deliver
        flash[:notice] = "员工帐号创建成功！"
        redirect_to :action=>:index
      end # unless @member.save
    end # transaction
  end # def create

  def update
    if @member.update_attributes params[:member]
      flash[:notice] = "员工信息编辑成功"
      redirect_to :action=>:index
    else
      flash.now[:notice] = "员工信息编辑失败！"
      render :action=>:edit
    end # if ... update...
  end # def update

  def reset_passwd
    if @member.nil?
      alert "邮箱错误,请重新输入邮箱地址!"
    else
      new_passwd = @member.reset_passwd
      MemberMailer.send_password(@member, new_passwd).deliver
      render :index do |page|
        page.alert '新密码已经发送到你注册邮箱！'
      end #render
    end # if
  end # def reset_passwd

  def lock
    if @member.update_attribute :status, Member::STATUS_LOCKED
      render :text=>"success"
    else
      render :text=>"fail"
    end # if ...LOCKED
  end # def lock

  def unlock
    if @member.update_attribute :status, Member::STATUS_ACTIVE
      render :text => Member::STATUS_ACTIVE
    else
      render :text => "fail"
    end # if ... ACTIVE
  end # def unlock

private
  def find_member
    @member = Member.find params[:id]
  end
end

trunk/app/helpers/admin/members_helper.rb
module Admin::MembersHelper
  def choice_for_account_transaction
        box = [['银行转账',0]]
  end
  
  def choice_for_is_admin
       box = [['请选择',nil],['是',1],['否',0]]
  end
  
  def choice_for_is_ad_owner
       box = [['请选择',nil],['是',1],['否',0]]
  end
  
  def choice_for_is_publisher
       box = [['请选择',nil],['是',1],['否',0]]
  end
  
  def member_status(member)
    status = member.is_a?(Member) ? member.status : member.to_s.to_i
    t "member.status.#{status}"
  end
  
  def choices_member_status
      Member::ALL_STATUS.collect{|t| [member_status_fetch(t),t]}
  end

  def member_status_fetch(status)
      t "member.status.#{status}"
  end
end

trunk/app/helpers/members_helper.rb
module MembersHelper
end

trunk/app/helpers/my_company/members_helper.rb
module MyCompany::MembersHelper
  def choice_for_role
    role_ids = member_has_role_ids
    roles = Role.find :all, :conditions=>["id in (?)", role_ids]
    roles.collect { |r| [r.name, r.id] }
  end # def choice_for_role

  def member_has_role_ids
    role_ids = [::Role::ROLE_ADMIN]
    if current_user.party.is_valid_agent?
      role_ids << ::Role::ROLE_AGENT
    end # if ...agent?
    if current_user.party.is_valid_publisher?
      role_ids << ::Role::ROLE_PUBLISHER
    end # if ...publisher?
    if current_user.party.is_valid_ad_owner?
      role_ids << ::Role::ROLE_AD_OWNER
      role_ids << ::Role::ROLE_SALES
    end # if ...ad_owner?
    role_ids
  end # def member_has_roles
end

trunk/app/views/admin/members/_a.html.erb
<tr id="<%= element_id a%>">
           <td><%=format_time a.created_at%></td>
		    <td><%= a.operator.name%></td>
		    <td><%if a.operation == 0%>充值<%else%>提现<%end%></td>
		    <td>银行转账</td>
		    <td id="money"><%= format_money a.amount%></td>
		    <td id="money"><%= format_money a.balance%></td>	
</tr>		    
		    

trunk/app/views/admin/members/_m.html.erb
<tr id="<%= element_id m%>">
	<td><%=link_to m.real_name ,admin_member_path(m,:format=>:html)%></td>
	<td><%= m.party.name if m.party %></td>
	<td><%= m.real_name if m and m.real_name%></td>
	<td><%= (m.is_admin == true ? '是' : '否') %></td>
	<td><%= member_status(m)%></td>
</tr>

trunk/app/views/admin/members/faces.html.erb
<%page_title "充值页面"%>

<% javascript_tag do %>
  $(function(){
  	$('#faces_form').validate();
  });
<% end-%>

<div class="form">
<%form_tag supplement_admin_member_path(:id=>@member.id,:format=>:html),:method=>:post,:id=>"faces_form" do%>
  <fieldset>
   <span>充值金额：<%= text_field_tag 'amount','',:class=>"required",:size=>20%></span>
  </fieldset>
  <fieldset>
   <span>充值方式：<select name="op_way">
   	                  <%= options_for_select choice_for_account_transaction%>
                 </select>
   </span>
  </fieldset>
  
  <div class="buttons">
    <%= submit_tag '提交', :class=>'primary_button' %>
  </div>
                             
<%end%>                                
</div>

trunk/app/views/admin/members/index.html.erb
<%page_title '用户管理'
  side_bar 'admin_console'
%>

<h2>用户列表：</h2>

<div style="width:600px">
	<%form_tag admin_members_path(:format=>:html),:method=>:get,:id=>"admin_member_form" do%>
	<p><span>姓名：</span><%= text_field_tag 'name','',:size=>20%>
		<span>是否为管理员：</span>
			<select name="is_admin">
		       <%= options_for_select choice_for_is_admin%>
	       </select>
		<span>当前状态：</span>
		     <select name="status">
		     	<option value="">请选择</option>
		     	<%= options_for_select choices_member_status%>
		     </select>  
		<%=submit_tag '查找',:class=>'primary_button'%>             
	</p>
	<%end%>
</div>
<table id="admin_member_list" border="0" class="data_list stripped">
 <tr>
 	<th width="*">姓名</th>
    <th width="25%">合作伙伴</th>
 	<th width="15%">用户名称</th>
 	<th width="15%">管理员</th>
 	<th width="15%">当前状态</th>
 		
 </tr>
 <%= render :partial=>'m',:collection=>@members%>
 
 <%= will_paginate @members%>
</table>

trunk/app/views/admin/members/show.html.erb
<%page_title '用户详细信息'
  %>

<%javascript_tag do%>
   $(document).ready(function(){
   	  <% if @member.status == Member::STATUS_LOCKED%>
   	     $('#status_button').html("解锁用户");
   	  <%else%>
   	     $('#status_button').html("锁定用户");
   	  <%end%>
   });
<%end%>

<div class="section">
	<div class="head">
		<h2>用户所有信息：</h2>
	</div>
	
	<div class="body">
	<dl class="attributes">
	  <dt>电子邮件：</dt><dd><%= @member.email if @member.email%></dd>
	  <dt>用户姓名：</dt><dd><%= @member.real_name if @member.real_name%></dd>
	  <dt>账户余额：</dt><dd><%= format_money @member.party.account_balance if @member.party %></dd>
	  <dt>用户地址：</dt><dd><%= @member.party.address if @member.party and @member.party.address%></dd>
	  <dt>邮政编码：</dt><dd><%= @member.party.post_code if @member.party and @member.party.post_code%></dd>
	  <dt>联系方式：</dt><dd><%if @member.party and @member.party.phone_number%><%= @member.party.phone_number%><%end%></dd>
	  <dt>是否是管理员：</dt><dd><%if @member.is_admin ==1 %>是<%else%>否<%end%></dd>
	  
	  <dt>当前状态：</dt><dd><span id="current_status"><%= member_status(@member)%></span></dd> 	
     
	</div>
	<div class="buttons">
		 <%= link_to '',locked_Or_unlocked_admin_member_path(:id=>@member.id,:format=>:js),:method=>:post,:class=>'button remote',:id=>'status_button'%>
        <%= link_to '充值',faces_admin_member_path(:id=>@member.id,:format=>:html),:target=>"_bank",:class=>'button'%>
	</div>
</div>

<div class="section">
	<div class="body">
		<h3>最近十条充值记录：</h3>
		<table class="" border="0">
		  <tr>
		  	<th width="*">时间</th>
		  	<th width="15%">操作人</th>
		  	<th width="15%">操作</th>
		  	<th width="15%">操作方式</th>
		  	<th width="15%">金额</th>
		  	<th widht="15%">变动后金额</th>
		  </tr>
		  
		  <%for account_transaction in @account_transactions%>
		  <tr>
		    <td><%=format_time account_transaction.created_at%></td>
		    <td><%= account_transaction.operator.name%></td>
		    <td><%if account_transaction.operation == 0%>充值<%else%>提现<%end%></td>
		    <td>银行转账</td>
		    <td id="money"><%= format_money account_transaction.amount%></td>
		    <td id="money"><%= format_money account_transaction.balance%></td>
		  </tr>  		    
		  <%end-%>
		</table>
		<div class="buttons">
			<%= link_to '查看所有充值记录',show_records_admin_member_path(:id=>@member.id,:format=>:html),:target=>"_bank",:class=>'button'%>
		</div>
	</div>	
</div>

trunk/app/views/admin/members/show_records.html.erb
<%page_title "#{@member.name}所有充值记录"%>

<div class="section">
	<div class="body">
		<h2><%=@member.name%>所有充值记录</h2>
	</div>

<table class="" border="0" class="data_list stripped">
		  <tr>
		  	<th width="*">时间</th>
		  	<th width="15%">操作人</th>
		  	<th width="15%">操作</th>
		  	<th width="15%">操作方式</th>
		  	<th width="15%">金额</th>
		  	<th widht="15%">变动后金额</th>
		  </tr>
		  <%= render :partial=>'a',:collection=>@account_transactions%>
		  
		  <%= will_paginate @account_transactions %>
</table>


</div>