trunk/config/routes.rb
Adhub::Application.routes.draw do
  resources :ad_requests do
    post :shown, :clicked, :on=>:member
  end

  resources :parties do
    get :autocomplete_search, :on=>:collection
    post :archived, :on=>:member
  end

  resources :contracts do
    post :stop, :on=>:member
    put :renewal, :on=>:member
  end
  
  match '/members/my_account',:controller=>'members',:action=>'edit',:format=>:html

  resources :members do 
    get 'active', :on=>:member
    get 'check_email', 'forget_password_form', :on=>:collection
    post :resend_active_email, :on=>:collection
    post :forget_password_form,:on=>:collection
    get :modify_passwd,:on=>:collection
    post :update_passwd,:on=>:member
    post :supplement,:on=>:member
    get :faces,:on=>:member 
  end
  
  namespace :admin do
    resources :parties do
      post :save_account,:on=>:member
      resources :contracts
    end

    resources :contracts do
      put :renewal, :on=>:member
      post :stop, :on=>:member
    end
    resources :members do
      member do
        post :locked_Or_unlocked
        post :supplement
        get :show_records     
        get :faces
      end     
      get :autocomplete_search, :on=>:collection
    end

    resources :advertisements do
      post :approve, :on=>:member
    end
    
    resources :ad_containers do
      post :approve, :on=>:member     
    end
    
    resources :account_transactions

    resources :cash_claims
    
    resources :content_categories
    
    resources :sdks do
      get :next_step,:on=>:member
      post :upload_sdk,:on=>:member
    end
    match '/', :controller=>'members', :action=>'index'
  end

  namespace :my_company do
    resources :parties do
      get :show_account_transactions,:on=>:collection
    end
    resources :members do
      post :lock, :on=>:collection
      post :unlock, :on=>:collection
      post :reset_passwd, :on=>:collection
    end
  end
  
  namespace :ad_owner do
    resources :campaigns do
      post 'stop', 'execute', 'submit', 'set_budget', :on=>:member
      get 'budgets', :on=>:collection
      get 'budget', :on=>:member
      resources :publish_policies do
        post 'stop',:on=>:member
        post 'execute',:on=>:member
      end
    end
    
    match '/', :controller=>'console', :action=>'index'
    match '/console/select_ad_owner', :controller=>'console', :action=>'select_ad_owner'
    match '/ad_resources/:ad_format/:action(.:format)', :controller=>'ad_resources'

    resources :ad_resources
    
    resources :advertisements do
      post :submit_approve,:on=>:member
      post :revoke, :on=>:member
      post :stop, :on=>:member
      post :execute,:on=>:member
      
      resources :publish_policies do
         get :step_2,:on=>:member
         get :step_3,:on=>:member
         get :search,:on=>:member
         get :judge_successful_step_2,:on=>:member
         get :select_content_categories,:on=>:member
         post :stop,:on=>:member
         post :execute,:on=>:member
         post :decrease_ad_container,:on=>:member
         post :increase_ad_container,:on=>:member
         post :notice_to_price,:on=>:member
         post :save_step_3,:on=>:member
         post :save_content_categories,:on=>:member
      end
    end

    resource :report do
      get 'summary', 'daily', :on=>:member
    end
  end

  namespace :agent do
    match '/', :controller=>'console', :action=>:index
  end

  namespace :publisher do
    resources :black_lists
    resources :prices
    resources :publish_policies do
      get :ad_detail, :on=>:collection
    end

    resources :ad_containers do
       post :submission,:on=>:member
       get :show_identity,:on=>:member
    end

    resource :report do 
      get 'summary', 'daily', :on=>:member
    end
     
    resources :bank_accounts do 
       get :show_ex ,:on=>:collection 
       post :send_dynamic_pass ,:on=>:collection 
    end
    
    resources :cash_claims

    match '/', :controller=>'console', :action=>:index
  end

  namespace :member do
    resource :cash_claims
  end
  
  scope '/target/:target_type/:target_id'  do
    resources :approve_logs
  end
  
  resources :sdks do
    collection do
      get :sdks_list
    end
  end
  match 'sdks/:os_type/download',:controller=>'sdks',:action=>'download'
  
  resource :session 
  

  match '/', :controller=>'sites', :action=>'index', :as=>'main'
  match '/static/:action', :controller=>'sites'
  
  

end

trunk/app/models/party.rb
class Party < ActiveRecord::Base
  has_many :members
  has_many :contracts
  has_many :bank_accounts
  has_one :account
  has_one :black_list, :as=>:black_member
  has_many :approve_log, :as=>:target

  PARTY_TYPE_COMPANY=0
  PARTY_TYPE_PERSON=1
  ALL_PARTY_TYPE = [PARTY_TYPE_COMPANY, PARTY_TYPE_PERSON]
  
  AD_MAINTAINED_BY_CUSTOMER = 0
  AD_MAINTAINED_BY_SALES = 1
  AD_MAINTAINED_BY_ADMIN = 2
  ALL_AD_MAINTAINED_BY = [AD_MAINTAINED_BY_CUSTOMER,AD_MAINTAINED_BY_SALES,AD_MAINTAINED_BY_ADMIN]

  include Publisher
  include AdOwner
  include Agent
  
  validates_presence_of :name
  validates_presence_of :party_type
  validates_presence_of :address
  validates_presence_of :phone_number
  validates_presence_of :post_code
  validates_uniqueness_of :name

  def self.adhub_operator
    self.where(:adhub_operator=>true).first
  end

  def is_valid_agent?
    self.adhub_operator or self.has_valid_contract_for Contract::BUSINESS_TYPE_AGENT
  end

  def is_valid_publisher?
    self.adhub_operator or self.has_valid_contract_for Contract::BUSINESS_TYPE_PUBLISHER    
  end

  def is_valid_ad_owner?
    self.adhub_operator or self.has_valid_contract_for Contract::BUSINESS_TYPE_AD_OWNER        
  end
  
  def has_valid_contract_for(business_type)
    self.adhub_operator or self.contracts.of_business_type(business_type).valid.count == 1
  end

  def valid_contracts
    self.contracts.valid
  end

  def available_roles
    return Role.all if self.adhub_operator
    valid_contract_types = self.valid_contracts.collect { |c| c.business_type }
    Role.available_to_contract_types valid_contract_types
  end

  def account_balance
    self.create_account if self.account.nil?
    self.account.balance
  end

  def sales_email
    if self.sales_id
      return member.find(self.sales_id).email
    else
      nil
    end
  end

  def contract_of(business_type)
    self.contracts.of_business_type(business_type).first
  end

  def destroyable?
    self.contracts.count ==0
  end

  def balance_warn_parties
    if self.ad_owners.count > 0
      self.ad_owners.where("id in (select party_id from accounts where balance <= #{Contract::BALANCE_WARN} order by balance) and id not in (select party_id from contracts where expiration_processed = 1)")
    end
  end

  def expired_warn_parties
    if self.ad_owners.count > 0
      self.ad_owners.where("id in (select party_id from contracts where expiration_processed = 0 and TIMESTAMPDIFF(DAY, now(), expired_at) <= #{Contract::EXPIRED_WARN} order by expired_at)")
    end
  end

  alias_method :old_account, :account

  def account
    if self.old_account.nil?
      # puts "self(Party[#{self}, #{self.id}]).old_account is nil, create new one"
      self.create_account
    end
    self.old_account
  end

  def can_archived?
    self.contracts.where(:expiration_processed=>false).count == 0 and !self.archived
  end

  def has_enough_balance_to_run_ad
    self.account.balance > 100
  end
  
  private
  def share_rate(business_type, attribute, system_param)
    contract = self.contract_of business_type
    return 0 if contract.nil?
    rate = contract.send attribute
    if rate and rate > 0
      rate
    else
      SystemParameter.find_by_name(system_param).value
    end
  end

  # def create_account
  #   return self.account if self.account
  #   self.create_account :balance=>0
  # end
end

trunk/app/controllers/admin/parties_controller.rb
require "dynamic_query"
class Admin::PartiesController < Admin::AdminController
  include Imon::DynamicQuery
  before_filter :find_party, :only=>[:show,:save_account]

  def index
    exps = []
    exps << self.less_or_equal("contracts.expired_at", params[:min_expired]) if params[:min_expired] and !params[:min_expired].empty?
    exps << self.like("parties.name", params[:name]) if params[:name] and !params[:name].empty?
    exps << self.equal("parties.party_type", params[:party_type]) if params[:party_type] and !params[:party_type].empty?
    exps << self.not_equal("parties.id", current_user.party.id)
    exps << self.equal("contracts.business_type", params[:contract_business_type]) if params[:contract_business_type] and !params[:contract_business_type].empty?
    exps << self.equal("contracts.expired_at", params[:expired_at]) if params[:expired_at] and !params[:expired_at].empty?
    unless params[:archived] and !params[:archived].empty?
       exps << self.equal("parties.archived", false)
    end
    exps << self.or(self.is_null('parties.agent_id'), self.equal("parties.agent_id", current_user.party.id))
    @parties = Party.paginate :all, :conditions=>self.and(exps).conditions, :include=>"contracts", :order=>"name desc", :page=>params[:page], :per_page=>10
  end

  def show
    
  end

  def stop_contract
    @contract = Contract.find params[:id]
    @contract.stop!
  end
  
  def save_account
    if params[:amount] and params[:amount].to_f >0.0
        unless @party.account.save!(params[:amount].to_f)
          flash.now[:notice] = "充值不成功！"
          render :noting=>true
        else
          flash[:notice] = '充值成功！'
          render :action=>:show  
        end
    else
         flash.now[:notice] ='请正确填写充值金额。'
         render :action=>:show     
    end    
  end

private
  def find_party
    @party = Party.find params[:id]
  end
end

trunk/app/controllers/my_company/parties_controller.rb
require 'dynamic_query'
class MyCompany::PartiesController < MyCompany::MyCompanyController
  include Imon::DynamicQuery
  layout 'default'

  def show_account_transactions
    @party = current_user.party
    if @party.account.nil?
      @party.create_account
    end
    exps = expressions_from_params params, AccountTransaction
    over_time = Date.strptime(params[:over_time])+1  if params[:over_time]
    start_time = Date.strptime(params[:start_time]) if params[:start_time]
    exps = self.between(:created_at,start_time,over_time) if params[:start_time] 
    @account_transactions = @party.account.account_transactions.paginate :all,
      :conditions=>self.and(exps).conditions,
      :order=>'created_at desc',:page=>params[:page],
      :per_page=>10
  end
end

trunk/app/controllers/parties_controller.rb
# -*- coding: utf-8 -*-
require 'dynamic_query'
class PartiesController < ApplicationController
  include Imon::DynamicQuery
  layout "default"

  before_filter :authenticated
  before_filter :find_party, :only=>[:show, :edit, :update, :destroy, :archived]
  #before_filter :check_party_archived?, :only=>[:edit, :update, :destroy, :archived]

#  require_privilege :query_customer, :only=>[:index]
  require_privilege :modify_party, :only=>[:show, :edit, :update, :destroy, :archived], :data_object=>:@party
  require_privilege :new_party, :only=>[:new, :create]

  before_filter :check_privilege
  before_filter :choose_main_menu

  def index
    exps = []
    exps << self.like('parties.name', params[:name]) if params[:name] and !params[:name].empty?
    exps << self.equal('contracts.business_type', Contract::BUSINESS_TYPE_AD_OWNER)
    exps << self.equal('parties.party_type', params[:party_type]) if params[:party_type] and  !params[:party_type].empty?
    exps << self.less_or_equal('contracts.expired_at', Date.strptime(params[:expired_at])) if params[:expired_at] and !params[:expired_at].empty?
    unless params[:archived] and !params[:archived].empty?
      exps << self.equal('parties.archived', false)
    end
    exps << self.equal('parties.agent_id', current_user.party.id)
    ids = []
    if (params[:account_min] and !params[:account_min].empty?) or (params[:account_max] and !params[:account_max].empty?)
      if (params[:account_min] and !params[:account_min].empty?) and (params[:account_max] and !params[:account_max].empty?)
        accounts = Account.find_by_sql ["select party_id from accounts where balance between ? and ?", params[:account_min], params[:account_max]]
        accounts.collect {|a| ids << a.party_id }
      else
        if params[:account_min] and !params[:account_min].empty? 
          accounts = Account.find_by_sql ["select party_id from accounts where balance >= ?", params[:account_min]]
          accounts.collect {|a| ids << a.party_id }

        end
        if params[:account_max] and !params[:account_max].empty?
          accounts = Account.find_by_sql ["select party_id from accounts where balance <= ?", params[:account_max]]
          accounts.collect {|a| ids << a.party_id }
        end
      end
      exps << self.in("parties.id", ids) if ids.count>0
      exps << self.in("parties.id", [-1]) if ids.count==0
    end

    @parties = Party.paginate :all, :conditions=>self.and(exps).conditions, :include=>:contracts, :order=>"parties.created_at desc", :page=>params[:page], :per_page=>20
  end

  def new
    @party = Party.new
    unless current_user.party.nil?
      @contract = @party.contracts.new
      @contract.start_from = Date.today
      @contract.expired_at = Date.today.next_year
    end
  end

  def create
    @party = Party.new params[:party]
    @party.adhub_operator = false
    @party.agent = current_user.party if current_user.party
    Party.transaction do
      if @party.save!
        if current_user.party.nil?
          current_user.party=@party
          current_user.save!
          current_user.roles << ::Role.find_by_code(:admin)
        else
          if params[:contract]['start_from'].nil? or params[:contract]['start_from'].empty?
            params[:contract]['start_from'] = Time.now.to_date
          end # if params..start_from..
          if params[:contract]['expired_at'].nil? or params[:contract]['expired_at'].empty?
            params[:contract]['expired_at'] = Time.now.next_year.to_date
          end # if params..expired_at..
          @contract = @party.contracts.build params[:contract]
          @contract.business_type = Contract::BUSINESS_TYPE_AD_OWNER

          if @contract.save!
            redirect_to parties_path(:format=>:html)
          else
            render :action=>:new
            return
          end # if @contract.save
          return
        end
        redirect_to main_url
      end # if @party.save!
    end # .. transaction ..
    rescue ActiveRecord::RecordInvalid
      render :action => :new
  end # def create

  def update
    if params[:sales_email] and !params[:sales_email].empty?
      sales = current_user.party.members.where("id in (select member_id as id from members_roles where role_id = #{::Role::ROLE_SALES})").find_by_email params[:sales_email]
      if sales
        params[:party]['sales_id'] = sales.id
      else
        flash[:notice] = "您的公司没有该业务员，编辑失败！"
        render :action=>:edit
        return
      end
    end
    if @party.update_attributes params[:party]
      flash[:notice]="修改成功！"
      redirect_to :action=>:edit
    else
      render :action=>:edit
    end
  end

  def autocomplete_search
    members = current_user.party.members.where("id in (select member_id as id from members_roles where role_id = #{::Role::ROLE_SALES})").find :all, :conditions=>['email like ?', "%#{params[:term]}%"]
    return_v=[]
    unless members.count == 0
      members.collect {|m| return_v << m.email }
    end #unless
    render :json=>return_v
  end # def autocomplete_search

  def destroy
    if @party.destroyable?
      @party.destroy
    else
      flash[:notice]="此广告客户已经发布过广告，无法删除，只能中止合约！"
    end
  end

  def archived
    if @party.can_archived?
      @party.archived=true
      @party.save!
      logger.info "now archived party.id is #{@party.id}"
    else
      alert "合约没有中止，不能归档!"
    end
  end

  private
  def find_party
    @party = Party.find params[:id]
  end

  def choose_main_menu
    if current_user.party.nil?
      @active_menu = nil
    elsif current_user.party == @party
      @active_menu = 'mnu_my_company'
    else
      @active_menu = 'mnu_agent'
    end
  end
end

trunk/app/helpers/admin/parties_helper.rb
module Admin::PartiesHelper
  def choice_for_party_type
    Party::ALL_PARTY_TYPE.collect{|t|[party_type_for_fetch(t),t]}
  end

  def party_type_for_fetch(party_type)
    t "party.party_type.#{party_type}"
  end

  def choice_for_contract_business_type
    Contract::ALL_BUSINESS_TYPE.collect{|t|[business_type_for_fetch(t),t]}
  end

  def business_type_for_fetch(business_type)
    t "contract.business_type.#{business_type}"
  end
end

trunk/app/helpers/my_company/parties_helper.rb
module MyCompany::PartiesHelper
end

trunk/app/helpers/parties_helper.rb
# -*- coding: utf-8 -*-
module PartiesHelper
  def get_party_type(type)
    t "party.party_type.#{type}"
  end

  def party_type_select(form, method, options={})
    option_tags=[['公司', Party::PARTY_TYPE_COMPANY], ['个人', Party::PARTY_TYPE_PERSON]]
    form.select method, option_tags, options 
  end

  def party_type_select_tag(method, selected=nil, options={})
    option_tags=[['公司', Party::PARTY_TYPE_COMPANY], ['个人', Party::PARTY_TYPE_PERSON]]
    select_tag method, options_for_select(option_tags, selected), options
  end
  
  def choice_ad_maintained_by
    Party::ALL_AD_MAINTAINED_BY.collect{|t|[party_ad_maintained_by_fetch(t),t]}
  end
  
  def party_ad_maintained_by_fetch(ad_maintained_by)
    t "party.ad_maintained_by.#{ad_maintained_by}"
  end
end

trunk/app/views/parties/_f.html.erb
  <div class="form_error">
    <%= f.error_messages %>
  </div>
  <fieldset>
    <%= f.label :name, :class=>'form-label' %>
    <div class="group">
      <%= f.text_field :name, :class=>'required', :size=>30%>
      <span class="help">请填写公司名称或个人姓名。</span>
    </div>
  </fieldset>
  <fieldset>
    <%= f.label :party_type, :class=>'form-label' %>
    <%= party_type_select f, :party_type, :class=>'form-label' %>
  </fieldset>
  <fieldset>
    <%= f.label :address, :class=>'form-label' %>
    <%= f.text_field :address, :class=>'required', :size=>30, :maxlength=>300 %>
  </fieldset>
  <fieldset>
    <%= f.label :phone_number, :class=>'form-label' %>
    <%= f.text_field :phone_number, :size=>30, :maxlength=>50, :class=>'required' %>
  </fieldset>
  <fieldset>
    <%= f.label :post_code, :class=>'form-label' %>
    <%= f.text_field :post_code, :size=>6, :maxlength=>6, :class=>'required' %>
  </fieldset>

trunk/app/views/parties/_party.html.erb
<%
  @contract = party.contracts.where(:business_type => Contract::BUSINESS_TYPE_AD_OWNER).first
%>
<tr id="<%=element_id party %>">
	<td>
            <%= party.name %><br/>

        </td>
        <td><%= get_party_type party.party_type %></td>
	<td><% if party and party.sales_id %><%= link_to Member.find(party.sales_id).email, edit_party_path(party, :format=>:html) %><% end %></td>
        <td><%= party.contracts.first.expired_at %></td>
  <td align="center" id="exp_flag_<%= @contract.id %>">
    <%= @contract.expiration_processed ? "是": "否" %>
  </td>
  <td align="center" id="arch_flag_<%= party.id %>">
    <%= party.archived ? "是": "否" %>
  </td>
  <td>
    <div class="dropdown_menu">
      <ul class="menu">
	  <li><%= link_to (t "party.agent_operate.1"),edit_party_path(party,:format=>:html)%></li>
          <li><%= link_to (Contract.human_attribute_name :page_title_content), contract_path(@contract, :format=>:html) %></li>
          <% if !@contract.expiration_processed %>
          <li>
              <%= link_to (t "contract.operate.0"), stop_contract_path(@contract,:format=>:js),:method=>:post, :class=>'remote', :id=>"stop_bt" %>
          </li>
          <% end %>
          <%if current_user.has_manager_privilege?(party)%>
            <li><%= link_to '管理广告',"/ad_owner?p_id= #{party.id}"%></li> 
          <%end%>
          <li><%= link_to (t "party.agent_operate.4"), archived_party_path(party, :format=>:js), :method=>:post, :class=>"remote", :id=>"archived_bt_#{party.id}", :style=> (party.can_archived? ? 'display:block' : 'display:none' ) %></li>
          <% #if party.destroyable? %>
	  <%#= link_to '删除', party_path(party,:format=>:js),:class=>'delete'%>
          <%# end %>
      </ul>
    </div>
  </td>
</tr>

trunk/app/views/parties/edit.html.erb
<% if current_user.party==@party
       page_title '编辑基本信息'
       side_bar 'my_company'
   else
       page_title '编辑广告客户信息' if current_user.party.is_valid_agent?
       side_bar 'agent'
       include_js_file 'jquery.AutoComplete'
   end
 -%>

<% javascript_tag do -%>
  $(function(){
    $('#new_form').validate();
  });
<% end -%>

<div class="section">
  <div class="head">
    <h2 class="beside_site_logo">
        <% if current_user.party==@party %>
            编辑基本信息
        <%else
            if current_user.party.is_valid_agent?%>
                编辑广告客户信息
           <% end
        end%>
    </h2>
  </div>
  <div class="form">
  <% form_for :party, @party, :url=>party_path(@party, :format=>:html), 
     :html=>{:id=>'new_form', :method=>:put} do |f| -%>
  <%= render :partial=>'f', :locals=> {:f=>f} %>
  <fieldset>
  <% if current_user.party!=@party and current_user.party.is_valid_agent? %>
    <%= f.label :sales, :class=>'form-label' %>
    <% sales_email = Member.find(@party.sales_id).email if @party and @party.sales_id %>
    <%= text_field_tag :sales_email, sales_email, :class=>'txt_w', :size=>30 %>
  <% end %>
  </fieldset>
  
  <%if @party.is_valid_ad_owner?%>
    <fieldset>
    	<%=f.label :ad_maintained_by,:class=>"form-label"%>
    	<%=f.select :ad_maintained_by,choice_ad_maintained_by%>
    </fieldset>
  <%end%>
  <div class="buttons">
    <input type="submit" value="修改" class="primary_button"/>
  </div>
  <% end -%>
  </div>
</div>

<% javascript_tag do -%>
$(".txt_w").autocomplete({
  source: '/parties/autocomplete_search.json'
});
<% end -%>

trunk/app/views/parties/index.html.erb
<%page_title "广告客户管理"
  side_bar 'agent'
%>

<%= javascript_tag do -%>
$(function(){
    $('#search_date').datepicker({ autoSize:true,
                                    dateFormat :'yy-mm-dd'});                          
});
<% end -%>

<div class="section">
  <div class="head">
    <div class="buttons">
      <%= link_to '添加广告客户',new_party_path(:format=>:html),:class=>'button long'%>
    </div>
    
    <h2>广告客户管理</h2>	
    <div class="search">
       <% form_tag parties_path(:format=>:html), :method=>:get, :id=>'search_form' do %>
          <table>
            <tr>
              <td>名称：</td>
              <td><%= text_field_tag 'name', params[:name], :size=>8, :class=>"ml10" %></td>
              <td class="ml10"><span class="ml10">类型：</div></td>
              <td><%= party_type_select_tag 'party_type', params[:party_type], :include_blank=>true, :class=>"ml10" %></td>
	     </tr>
          <tr>
            <td>中止日期早于：</td>
            <td colspan="3"><%= text_field_tag 'expired_at', params[:expired_at], :size=>5, :id=>'search_date', :class=>"ml10" %></td>
	  </tr>
          <tr>
            <td>账户资金：</td>
            <td><%= text_field_tag 'account_min', params[:account_min], :size=>3, :class=>"ml10" %><span class="ml10">~</span>
              <%= text_field_tag 'account_max', params[:account_max], :size=>3, :class=>"ml10" %>
            </td>
            <td>
              <%= check_box_tag :archived, 1,params[:archived], :class=>"ml10" %>
              <span>包含已归档客户</span>
	    </td>
            <td>
              <%= submit_tag '查询', :class=>'primary_button ml10' %>
	    </td>
	  </tr>
          <tr>
            <td><%= Contract.human_attribute_name :fast_search %>:</td>
            <td colspan="3"><span class="ml10"><%= link_to (t "contract.fast_search.0"), parties_path(:expired_at=>Time.now.to_date.advance(:months=>1).strftime("%Y-%m-%d"), :format=>:html) %>
              <%= link_to (t "contract.fast_search.1"), parties_path(:account_max=> Contract::BALANCE_WARN,:format=>:html) %></span>
	    </td>
          </tr>
	</table>
       <% end %>
    </div>		
  </div>

  <div class="body">
   <table class="data_list stripped">
     <tr class="head">
     	<th width="*"><%= Party.human_attribute_name :name %></th>
        <th width="10%"><%= Party.human_attribute_name :party_type %></th>
        <th width="10%"><%= Party.human_attribute_name :sales %></th>
        <th width="20%">广告主合约</th>
        <th width="15%"><%= Contract.human_attribute_name :expiration_processed %></td>
        <th width="10%"><%= Party.human_attribute_name :archived %></td>
     	<th width="15%"><%= Party.human_attribute_name :agent_operate %></th>
     </tr>
     <%= render :partial=>'party',:collection=>@parties %>
   </table>
   <%= will_paginate @parties %>	
  </div>
</div>

trunk/app/views/parties/new.html.erb
<% if current_user.party.nil?
       page_title '补充信息'
   else
       if current_user.party.is_valid_agent?
           page_title '添加广告客户'
       end
   end
 -%>

<% javascript_tag do -%>
  $(function(){
    $('#new_form').validate();
    Fusion.use_feature(InitDatepicker);
  });
<% end -%>

<div class="aside">
  <div class="head">
    <h2>帮助信息</h2>
  </div>

  <div class="body">
    <p>首次登录的普通用户,系统提示输入补充“业务伙伴”信息。只有输入“业务伙伴”信息后才能签订各类业务合约,开着业务活动。"代理商"可以任意添加自己的“广告客户（业务伙伴）”。</p>
  </div>
</div>

<div class="form with_aside" id="new">
  <div class="head">
    <h2 class="beside_site_logo">
        <% if current_user.party.nil? %>
            补充信息
        <%else
            if current_user.party.is_valid_agent?%>
                添加广告客户
           <% end
        end%>
    </h2>
  </div>

  <%= error_messages_for :party %>
  <%= error_messages_for :contract if @contract %>
  
  <% form_for :party, @party, :url=>parties_path(:format=>:html), 
     :html=>{:id=>'new_form'} do |f| -%>
  
   <%= render :partial=>'f', :locals=> {:f=>f} %>

<% if current_user.party and current_user.party.is_valid_agent? %>
   <div class="head">
    <h2 class="beside_site_logo">合约信息 </h2>
   </div>
   <%= fields_for :contract, @contract, :id=>'contract_field' do |c| -%>
     <fieldset>
       <%= c.label :contact_person, :class=>'form-label' %>
       <%= c.text_field :contact_person, :size=>20, :maxlength=>30, :class=>'required' %>
     </fieldset>
     <fieldset>
       <%= c.label :mobile_phone, :class=>'form-label' %>
       <%= c.text_field :mobile_phone, :size=>11, :maxlength=>11, :class=>'required number' %>
     </fieldset>
     <fieldset>
       <%= c.label :start_from, :class=>'form-label' %>
       <%= c.text_field :start_from, :size=>20, :class=>'date-field' %>
     </fieldset>
     <fieldset>
       <%= c.label :expired_at, :class=>'form-label' %>
       <%= c.text_field :expired_at, :size=>20, :class=>'date-field' %>
     </fieldset>
   <% end -%>
<% end %>
  <div class="buttons">
    <input type="submit" value="保存" class="primary_button"/>
  </div>
<% end -%>
</div>

trunk/app/views/parties/show.html.erb
<%page_title "查看基本信息"
  side_bar 'my_company'
%>

<div class="section">
  <div class="head">    
    <h2>查看基本信息</h2>		
  </div>	
  
  <div class="body">
    <table>
      <tr>
        <td class="content"><%= Party.human_attribute_name :name %>:</td>
        <td class="content"><%= current_user.party.name %></td>
      </tr>
      <tr>
        <td class="content"><%= Party.human_attribute_name :party_type %>:</td>
        <td class="content"><%= get_party_type current_user.party.party_type %></td>
      </tr>
      <tr>
        <td class="content"><%= Party.human_attribute_name :address %>:</td>
        <td class="content"><%= current_user.party.address %></td>
      </tr>
      <tr>
        <td class="content"><%= Party.human_attribute_name :phone_number %>:</td>
        <td class="content"><%= current_user.party.phone_number %></td>
      </tr>
      <tr>
        <td class="content"><%= Party.human_attribute_name :post_code %>:</td>
        <td class="content"><%= current_user.party.post_code %></td>
      </tr>
    </table>
  </div>
</div>