trunk/config/routes.rb
Adhub::Application.routes.draw do
  resources :ad_requests do
    post :shown, :clicked, :on=>:member
  end

  resources :parties do
    get :autocomplete_search, :on=>:collection
    post :archived, :on=>:member
  end

  resources :contracts do
    post :stop, :on=>:member
    put :renewal, :on=>:member
  end
  
  match '/members/my_account',:controller=>'members',:action=>'edit',:format=>:html

  resources :members do 
    get 'active', :on=>:member
    get 'check_email', 'forget_password_form', :on=>:collection
    post :resend_active_email, :on=>:collection
    post :forget_password_form,:on=>:collection
    get :modify_passwd,:on=>:collection
    post :update_passwd,:on=>:member
    post :supplement,:on=>:member
    get :faces,:on=>:member 
  end
  
  namespace :admin do
    resources :parties do
      post :save_account,:on=>:member
      resources :contracts
    end

    resources :contracts do
      put :renewal, :on=>:member
      post :stop, :on=>:member
    end
    resources :members do
      member do
        post :locked_Or_unlocked
        post :supplement
        get :show_records     
        get :faces
      end     
      get :autocomplete_search, :on=>:collection
    end

    resources :advertisements do
      post :approve, :on=>:member
    end
    
    resources :ad_containers do
      post :approve, :on=>:member     
    end
    
    resources :account_transactions

    resources :cash_claims
    
    resources :content_categories
    
    resources :sdks do
      get :next_step,:on=>:member
      post :upload_sdk,:on=>:member
    end
    match '/', :controller=>'members', :action=>'index'
  end

  namespace :my_company do
    resources :parties do
      get :show_account_transactions,:on=>:collection
    end
    resources :members do
      post :lock, :on=>:collection
      post :unlock, :on=>:collection
      post :reset_passwd, :on=>:collection
    end
  end
  
  namespace :ad_owner do
    resources :campaigns do
      post 'stop', 'execute', 'submit', 'set_budget', :on=>:member
      get 'budgets', :on=>:collection
      get 'budget', :on=>:member
      resources :publish_policies do
        post 'stop',:on=>:member
        post 'execute',:on=>:member
      end
    end
    
    match '/', :controller=>'console', :action=>'index'
    match '/console/select_ad_owner', :controller=>'console', :action=>'select_ad_owner'
    match '/ad_resources/:ad_format/:action(.:format)', :controller=>'ad_resources'

    resources :ad_resources
    
    resources :advertisements do
      post :submit_approve,:on=>:member
      post :revoke, :on=>:member
      post :stop, :on=>:member
      post :execute,:on=>:member
      
      resources :publish_policies do
         get :step_2,:on=>:member
         get :step_3,:on=>:member
         get :search,:on=>:member
         get :judge_successful_step_2,:on=>:member
         get :select_content_categories,:on=>:member
         post :stop,:on=>:member
         post :execute,:on=>:member
         post :decrease_ad_container,:on=>:member
         post :increase_ad_container,:on=>:member
         post :notice_to_price,:on=>:member
         post :save_step_3,:on=>:member
         post :save_content_categories,:on=>:member
      end
    end

    resource :report do
      get 'summary', 'daily', :on=>:member
    end
  end

  namespace :agent do
    match '/', :controller=>'console', :action=>:index
  end

  namespace :publisher do
    resources :black_lists
    resources :prices
    resources :publish_policies do
      get :ad_detail, :on=>:collection
    end

    resources :ad_containers do
       post :submission,:on=>:member
       get :show_identity,:on=>:member
    end

    resource :report do 
      get 'summary', 'daily', :on=>:member
    end
     
    resources :bank_accounts do 
       get :show_ex ,:on=>:collection 
       post :send_dynamic_pass ,:on=>:collection 
    end
    
    resources :cash_claims

    match '/', :controller=>'console', :action=>:index
  end

  namespace :member do
    resource :cash_claims
  end
  
  scope '/target/:target_type/:target_id'  do
    resources :approve_logs
  end
  
  resources :sdks do
    collection do
      get :sdks_list
    end
  end
  match 'sdks/:os_type/download',:controller=>'sdks',:action=>'download'
  
  resource :session 
  

  match '/', :controller=>'sites', :action=>'index', :as=>'main'
  match '/static/:action', :controller=>'sites'
  
  

end

trunk/app/controllers/ad_owner/ad_groups_controller.rb
# -*- coding: utf-8 -*-
class AdOwner::AdGroupsController < AdOwner::AdOwnerController
  before_filter :find_campaign, :except=>[:compare_price]
  before_filter :find_ad_group, :except=>[:index, :new, :create, :compare_price]

  def new
    @ad_group = @campaign.ad_groups.new
    @ad_group.start_from = @campaign.start_from
    @ad_group.end_to = @campaign.end_to
  
    logger.info CallToAction.actions
  end

  def create
    @ad_group = @campaign.ad_groups.build params[:ad_group]
    @ad_group.creating = true
    if @ad_group.save
      redirect_to edit_ad_owner_campaign_ad_group_url(@campaign, @ad_group, :step=>2, :format=>:html)
    else
      render :action=>:new
    end
  end

  def edit
    @content_categories = ContentCategory.where(:for_ad_container => true)
    render :action=>'edit_step_2' if '2' == params[:step] or @ad_group.creating
  end


  def update
    creating = @ad_group.creating
    @ad_group.creating = false
    logger.info "ad_group's call_to_action is #{@ad_group.call_to_action}"

    if @ad_group.update_attributes params[:ad_group]
      if params[:content_categories]
          ids = params[:content_categories].keys
          @ad_group.content_categories.clear
          ids.each do |element|
             content_category = ContentCategory.find element.to_i
             @ad_group.content_categories << content_category
          end                 
      end
      
      if creating
        redirect_to new_ad_owner_ad_group_advertisement_url(@ad_group, :format=>:html)
      else
        redirect_to ad_owner_campaign_ad_group_url(@campaign, @ad_group, :format=>:html)
      end
    else
      if '2' == params[:step]
        render :action=>:edit_step_2
      else
        render :action=>:edit
      end
    end
  end
  
  def destroy
    @ad_group = @campaign.ad_groups.find params[:id]
    if @ad_group.destroyable?
      @ad_group.destroy
      unless 'table' == params[:from]
        update_page_redirect_to ad_owner_campaign_url(@campaign)
        return
      end
    else
      alert '现在不能删除。'
    end
  end
  
 def revoke
    @ad_group.revoke!
    reshow_or_replace_tr
  end
  
  def stop
    @ad_group.stop!
    @message = '本广告组包含的所有广告都已停止投放。'
    reshow_or_replace_tr
  end
 
  def execute
    @ad_group.execute!
    @message = '本广告组包含的所有通过审核的广告已处于正常投放状态。'
    reshow_or_replace_tr
  end

  def submit
    @ad_group.submit!
    @message = '本广告组包含的所有编辑中的广告已提交审核。'
    reshow_or_replace_tr
  end

  def compare_price
    result = Advertisement.compare_price params[:pay_method_id].to_i, params[:price]
    logger.info "result = #{result}"
    case result
    when 1
      @message = '您的出价目前是最高的。'
    when 0
      @message = '您的出价目前是最低的。'
    else
      per = "#{( result * 1000.0 / 10.0).to_i}%"
      @message = t("compare_price_result.#{  (result * 100 / 33).to_i }", :per=>per)
    end
    render :text=>@message, :layout=>nil
  end

  private
  def find_campaign
    @campaign = current_user.campaigns.find params[:campaign_id]
  end

  def find_ad_group
    @ad_group = @campaign.ad_groups.find params[:id]
  end
  
  def reshow_or_replace_tr
    if 'table' == params[:from]
      render :action=>'replace_tr'
    else
      flash[:notice] = @message
      update_page_redirect_to ad_owner_campaign_ad_group_url(@campaign,@ad_group)
    end     
  end
end

trunk/app/controllers/ad_owner/ad_owner_controller.rb
class AdOwner::AdOwnerController < ApplicationController
  layout 'default'
  select_main_menu 'mnu_ad_owner'

  before_filter :authenticated
  
  def catch_ad_owner
      if session[:party] != nil && session[:party].is_a?(Party)
         return session[:party]
      else
         return current_user.party
      end
  end
end

trunk/app/controllers/ad_owner/ad_resources_controller.rb
# -*- coding: utf-8 -*-
class AdOwner::AdResourcesController < AdOwner::AdOwnerController
  layout nil

  before_filter :find_ad_format, :only=>[:new, :upload]
  
  def index
    @advertiesments = catch_ad_owner.advertiesments.paginate :order=>'name',:page=>params[:page],:per_page=>10
  end

  def new
    render :action=>"new_#{@ad_format.name}"
  end
   
  def upload
    begin
      @ad_format.check_file_type(params[:resource_name], params[:Filename])
    rescue ArgumentError => ex
      render :json=>{ :error => ex.message }
      return
    end

    @resource = AdResource.new :ad_format => @ad_format, :name=>params[:resource_name], :member=>current_user
    @resource.file= params[:resource_file]
    logger.info "resource name is #{@resource.name}"
    logger.info "is image resource? #{@resource.ad_format.is_image_resource(@resource.name)}"
    if @resource.ad_format.is_image_resource(@resource.name)
      logger.info 'find size code now'
      begin
        @resource.size_code = @resource.ad_format.size_code_for_resource_image(@resource.name, @resource.file).to_s
      rescue ArgumentError => ex
        render :json=> { :error=> ex.message }
        return
      end
    end
    if @resource.save
      render :json=>{ :resource_id=> @resource.id, :url=>@resource.file.url, 
        :name=>@resource.name, :format=>@ad_format.name, :size=>@resource.size_code }
    else
      render :json=>{ :error=>@resource.errors.full_messages.join("\n") }
    end
  end

  def destroy
    @ad_resource = current_user.ad_resources.find params[:id]
    if @ad_resource.advertisement.nil? or (@ad_resource.advertisement.editing?)
      @ad_resource.destroy
    else
      alert '现在不能执行此操作。'
    end
  end

  private

  def find_ad_format
    @ad_format = AdFormat.of_name params[:ad_format]
    raise ActiveRecord::RecordNotFound if @ad_format.nil?
  end
end

trunk/app/controllers/ad_owner/advertisements_controller.rb
# -*- coding: utf-8 -*-
require 'dynamic_query'
class AdOwner::AdvertisementsController < AdOwner::AdOwnerController
  # before_filter :find_ad_group
  include Imon::DynamicQuery
  before_filter :find_advertisement, :except=>[:index, :new, :create]
  def index
    exps = expressions_from_params params, Advertisement
    @advertisements = catch_ad_owner.advertisements.paginate :conditions=>self.and(exps).conditions,:order=>'name',:page=>params[:page],:per_page=>10
    if @advertisements==nil
      logger.info "++++++++++++++++++it nil"
    end
  end

  def new
    @advertisement = catch_ad_owner.advertisements.new
  end

  def create
    @advertisement = catch_ad_owner.advertisements.build params[:advertisement]
    # @advertisement.call_to_action_params = params[:call_to_action_params]
    begin
      Advertisement.transaction do
        if @advertisement.save!
          resource_ids = params[:resource_ids].split(',').collect { |id| id.to_i}
          resource_ids.each do |resource_id|
            link_resource_to_advertisement resource_id, @advertisement
          end

          if params[:text_resource]
            params[:text_resource].each_pair do |resource_name, text|
              create_text_resource @advertisement, resource_name, text
            end
          end
        end
      end
      redirect_to ad_owner_advertisements_path(:format=>:html)

    rescue ActiveRecord::RecordInvalid => ex
    render :action=>:new
    end
  end

  def update
    begin
      @advertisement.attributes = params[:advertisement]
      @advertisement.call_to_action_params = params[:call_to_action_params]
      if @advertisement.save
        resource_ids = params[:resource_ids].split(',').collect { |id| id.to_i}
        remove_unused_non_text_resource resource_ids, @advertisement
        resource_ids.each do |resource_id|
          logger.info 'now link resource #{resource_id} to ad.'
          link_resource_to_advertisement resource_id, @advertisement
        end
        if params[:text_resource]
          params[:text_resource].each_pair do |resource_name, text|
            update_text_resource @advertisement, resource_name, text
          end
        end
      end
      redirect_to ad_owner_advertisement_url(@advertisement, :format=>:html)
    rescue ActiveRecord::RecordInvalid => ex
    render :action=>:edit
    end
  end

  def submit_approve
    if @advertisement.waiting_submit_approve?
    @advertisement.submit_approve!
    end
    reshow_or_replace_tr
  end

  def revoke
    @advertisement.revoke!
    reshow_or_replace_tr
  end

  def stop
    @advertisement.stop!
    reshow_or_replace_tr
  end

  def execute
    @advertisement.execute!
    reshow_or_replace_tr
  end

  def destroy
    if @advertisement.destroyable?
      unless @advertisement.destroy
      alert '删除不成功！'
      else
        render :update do |page|
          page.remove element_id @advertisement
        end
      end
    end
  end

  private

  def find_advertisement
    @advertisement = catch_ad_owner.advertisements.find params[:id]
  end

  def remove_unused_non_text_resource(used_resource_ids, advertisement)
    advertisement.ad_resources.each do |res|
      unless res.is_text_resource or used_resource_ids.include?(res.id)
      advertisement.ad_resources.delete res
      res.destroy
      end
    end
  end

  def link_resource_to_advertisement(resource_id, advertisement)
    resource = AdResource.find resource_id
    return unless current_user == resource.member and resource.advertisement.nil?
    advertisement.ad_resources << resource
  end

  def create_text_resource(advertisement, resource_name, text)
    ad_format = advertisement.ad_format
    return unless ad_format.is_text_resource(resource_name)
    advertisement.ad_resources.create! :member=>current_user, :ad_format=>advertisement.ad_format,
    :name=>resource_name, :text=>text
  end

  def update_text_resource(advertisement, resource_name, text)
    ad_format = advertisement.ad_format
    return unless ad_format.is_text_resource(resource_name)
    old_resource = advertisement.resource_of_name(resource_name)
    if old_resource
    old_resource.update_attributes! :text => text
    else
    advertisement.ad_resources.create! :member=>current_user, :ad_format=>advertisement.ad_format,
    :name=>resource_name, :text=>text
    end
  end

  def reshow_or_replace_tr
    if 'table' == params[:from]
    render :action=>'replace_tr'
    else
    update_page_redirect_to ad_owner_advertisement_url( @advertisement)
    end
  end

  protected
  def expression_for_name(name)
    self.like(:name,name)
  end
  
  def expression_for_status(status)
    self.equal(:status,status)
  end
end

trunk/app/controllers/ad_owner/console_controller.rb
class AdOwner::ConsoleController < AdOwner::AdOwnerController
  def index  
    if params[:p_id]
      party = Party.find params[:p_id]
      session[:party] = party
    end
    
      respond_to do |format|
        format.html
        format.mobile { render :layout=>'mobile' }
      end
  end
  
  def select_ad_owner
    @ad_owners = current_user.delegated_ad_owners.paginate :order=>'name',:page=>params[:page],:per_page=>10
  end
end

trunk/app/helpers/ad_owner/ad_groups_helper.rb
module AdOwner::AdGroupsHelper
end

trunk/app/helpers/ad_owner/ad_resources_helper.rb
module AdOwner::AdResourcesHelper
end

trunk/app/helpers/ad_owner/advertisements_helper.rb
module AdOwner::AdvertisementsHelper
  def advertisement_status(ad)
    status = ad.is_a?(Advertisement) ? ad.status : ad
    t "advertisement.status.#{status}"
  end

  def image_resource(resource, options={})
    return '' if resource.nil? or resource.file.nil?
    image_tag resource.file.url, options
  end

  def text_of_resource(resource)
    resource.nil? ? '' : resource.text
  end
  
  def publsh_policy_status(pp)
    status = pp.is_a?(PublishPolicy) ? pp.status : pp.to_s.to_i
    t "publish_policy.status.#{status}"
  end
end

trunk/app/helpers/ad_owner/campaigns_helper.rb
module AdOwner::CampaignsHelper
  def campaign_status_icon(campaign)
    if campaign.running?
      image = 'campaign_running.png'
    else
      image = 'campaign_stopped.png'
    end
    image_tag image
  end
end

trunk/app/helpers/ad_owner/console_helper.rb
module AdOwner::ConsoleHelper
  # TODO implement all count methods
  # def ad_group_count
  #  AdGroup.count :include=>:campaign, :conditions=>['campaigns.member_id = ?', current_user.id]
  # end

  def ad_count
    current_user.party.campaigns.inject(0) { |sum, c| sum + c.total_ad_count }
  end

  def effective_ad_count
    current_user.party.campaigns.inject(0) { |sum, c| sum + c.effective_ad_count }    
  end

  def click_count
    current_user.party.campaigns.inject(0) { |sum, c| sum + c.click_count }    
  end

  def impression_count
    current_user.party.campaigns.inject(0) { |sum, c| sum + c.impression_count }    
  end
end

trunk/app/helpers/ad_owner/publish_policies.helper.rb
module AdOwner::PublishPolicies
  def publsh_policy_status(pp)
    status = pp.is_a?(PublishPolicy) ? pp.status : pp.to_s.to_i
    t "publish_policy.status.#{status}"
  end
end

trunk/app/helpers/ad_owner/reports_helper.rb
module AdOwner::ReportsHelper
end

trunk/app/views/ad_owner/publish_policies/_ad.html.erb
<li id="<%= element_id ad%>"><%= link_to ad.name,increase_ad_container_ad_owner_advertisement_publish_policy_path(@advertisement,@publish_policy,:ad_container_id=>ad.id,:format=>:js),'data-method'=>:post,:class=>'remote'%></li>

trunk/app/views/ad_owner/publish_policies/_ad_ex.html.erb
<li id="<%= element_id ad_ex%>"><%= link_to ad_ex.name,decrease_ad_container_ad_owner_advertisement_publish_policy_path(@advertisement,@publish_policy,:ad_container_id=>ad_ex.id,:format=>:js),'data-method'=>:post,:class=>'remote'%></li>

trunk/app/views/ad_owner/publish_policies/new.html.erb
<%page_title '发布广告创意'
  side_bar 'ad_owner'
%>

<% javascript_tag do %>
$(function(){
Fusion.use_feature(InitDatepicker);
});
<% end -%>

<div class="form">
	<div class="head">
		<h2>发布广告创意</h2>
	</div>
	
	<%= error_messages_for :publish_policy %>	
	<%= form_for @publish_policy,:as=>:publish_policy,:url=>ad_owner_advertisement_publish_policies_path(@advertisement,@publish_policy,:format=>:html),
		           :html=>{:class=>'valiable',:method=>:post, :id=>'publish_policy_form'} do |f|%>
		<fieldset>
			<%= f.label :name,:class=>'form-label'%>
			<%= f.text_field :name,:size=>30,:class=>'required'%>
		</fieldset>
		<fieldset>
		 <%= f.label :campaign_id,:class=>'form-label'%>
		 <select name="publish_policy[campaign_id]">
		 <%if @campaigns %>
		   <%for campaign in @campaigns%>
		     <option value=<%=campaign.id%>><%= campaign.name%></option>
		   <%end%>
		 <%end%>
		 </select>
		</fieldset>
		<fieldset>
		   <%= f.label :channel_id,:class=>"form-label"%>
		   <select name="publish_policy[channel_id]">
		   	<%if @channels%>
		   	<%for channel in @channels%>
		      <option value=<%= channel.id%>><%= channel.name%></option>
		    <%end%>
		    <%end%>	
		   </select>
		</fieldset>
		<fieldset>
	       <%= f.label :start_from,:class=>'form-label'%>
	       <%= f.text_field :start_from,:value=>"#{@publish_policy.start_from}",:size=>30,:class=>'required date-field'%>		
		</fieldset>
		<fieldset>
			<%=f.label :end_to,:class=>'form-label'%>
			<div class="group">
			<%=f.text_field :end_to,:size=>30,:class=>'date-field'%>
			<span class="help">可选</span>
			</div>
		</fieldset>
		<fieldset>
		  <%= f.label :pay_method_id,:class=>'form-label'%>
		  <select name="publish_policy[pay_method_id]" class="required">
		  	<%if @pay_methods%>
		  	<%for pay_method in @pay_methods%>
		  	  <option value=<%= pay_method.id%>><%= pay_method.note%></option>
		  	<%end%>
		  	<%end%>
		  </select>
		</fieldset>
		<fieldset>
		    <%= f.label :daily_budget,:class=>'form-label'%>
		    <div class="group">
		    <%= f.text_field :daily_budget,:class=>'number',:min=>0%>
		    <span class="help">可选</span>
		    </div>
		 </fieldset>
		
		<fieldset>
			<%= f.label :call_to_action,:class=>'form-label'%>
			<%= call_to_action_select f, :call_to_action %>
		</fieldset>
		<div class="buttons">
		<%= f.submit "下一步",:class=>'primary_button'%>  
		</div>      
	<%end%>
</div>

trunk/app/views/ad_owner/publish_policies/search.html.erb
<ul class="data_list" id="ad_containers_list" style="float: right;width:100px">
   <%= render :partial=>'ad',:collection=>@ad_containers%>	
</ul>

trunk/app/views/ad_owner/publish_policies/select_content_categories.html.erb
<%page_title '选择内容条目'
  side_bar 'ad_owner'
%>

<div class="section">
	<div class="head">
		<h2>选择内容条目</h2>
	</div>
	
	<div class="form">
	   <h3>内容条目：</h3>
	   <%= form_tag save_content_categories_ad_owner_advertisement_publish_policy_path(@advertisement,@publish_policy,:format=>:html),'data-method'=>:post%>	
	   <%for cc in @content_categories%>
	     <%= check_box_tag "content_categories[#{cc.id}]"%><%= cc.name%> 
	   <%end%>
	   <div class="buttons">
	     <%= submit_tag '下一步',:class=>'primary_button'%>
	   </div>
	</div>
</div>

trunk/app/views/ad_owner/publish_policies/show.html.erb
<%page_title "#{@publish_policy.name}策略详细页面"
  side_bar 'ad_owner'
%>

<div class="section">
	<div class="head">
		<h2><%= @publish_policy.name %>策略详细页面</h2>
	</div>
	
	<dl class="attributes">
		<dt>名称：</dt>
		<dd><%= @publish_policy.name%></dd>
		<dt>活动：</dt>
		<dd><%if @publish_policy.channel.name%><%= link_to @publish_policy.channel.name,ad_owner_campaign_path(@publish_policy.channel,:format=>:html)%><%end%></dd>
		<dt>状态：</dt>
		<dd><%=publsh_policy_status(@publish_policy)%></dd>
		<dt>每日预算：</dt>
		<dd><%=format_money @publish_policy.daily_budget%>&nbsp;&nbsp;(今日已用：<%=format_money @publish_policy.used_daily_budget%>)</dd>
		<dt>开始日期：</dt>
		<dd><%=format_date @publish_policy.start_from%></dd>
		<dt>结束日期：</dt>
		<dd><%=format_date @publish_policy.end_to%></dd>
		<dt>渠道：</dt>
		<dd><%if @publish_policy.channel%><%=@publish_policy.channel.name %><%end%></dd>
		<dt>发布目标：</dt>
		<dd>
			<%if @publish_policy.ad_containers.size > 0%>
			<ul class="data_list">
			  <%for ad in @publish_policy.ad_containers%>
			    <li><%= ad.name%></li>
			  <%end%>
			</ul>
			<%else%>
			  没有目标设置
			<%end%> 	
	    </dd>
	    <dt>出价：</dt>
	    <dd>
	    	<%if @publish_policy.bid_price%>
	    	  <%= format_money @publish_policy.bid_price %>
	    	<%end%>
	    </dd>		
	</dl>
	<div class="buttons">
		<%= link_to '返回',ad_owner_advertisement_path(@advertisement,:format=>:html),:class=>'primary_button'%>
	</div>
</div>

trunk/app/views/ad_owner/publish_policies/step_2.html.erb
<%page_title "发布广告创意"
  side_bar 'ad_owner'
%>

<%javascript_tag do%>
$(function(){
  $('.block_02_load').load("/ad_owner/advertisements/"+<%= @advertisement.id%>+"/publish_policies/"+<%=@publish_policy.id%>+"/search.html?layout=false");	
});

<%end -%>

<div class="section">
	<div class="head">
		<h2>请在渠道<%= @advertisement.name%>中指定具体发布目标</h2>
    </div>
    
	 
    <table>
        <tr>       	
       <td width="160px">
          <h3>已选中的发布目标：</h3>
          <ul class="data_list" id="ad_containers_ex_list" style="float: right">
           	<%= render :partial=>'ad_ex',:collection=>@ad_containers_ex%>
          </ul>                		
       </td>
       <td width="180px"></td>   
       <td class="block_02" width="180px">
       	
		<div class="search">
	   	<%form_tag search_ad_owner_advertisement_publish_policy_path(@advertisement,@publish_policy,:format=>:html),
	   		:method=>:get,:id=>'search_form',:remote=>true,
	   		'data-update'=>'#search_result' do %>
			名称：<%= text_field_tag :name,params[:name],:size=>'4'%>
		   <%= submit_tag '查询',:class=>'primary_button',:style=>'width:50px'%>
		<%end%>
		</div>				
	   
	   <h3>请选择发布目标：</h3>
       <div class="block_02_load" id="search_result">
       	     	      
       </div>
       </td>
       </tr>
    </table>
    <div class="buttons">
       <%= link_to '下一步',judge_successful_step_2_ad_owner_advertisement_publish_policy_path(@advertisement,@publish_policy,:format=>:html),:class=>'primary_button'%>
    </div>    
</div>

trunk/app/views/ad_owner/publish_policies/step_3.html.erb
<%page_title "出价设置"
  side_bar "ad_owner"
%>
<%javascript_tag do%>
$(function(){
  $('#publish_policy_form').validate();
  
  $('input#base_pri').change(function(){	
	var price = $(this).val();
  	$.post("<%= notice_to_price_ad_owner_advertisement_publish_policy_path(@advertisement,@publish_policy,:format=>:json)%>",
  	       add_csrf_param({b_price:price}),
  	       function(response){
  	       	 $('#notice').html(response.result);
  	       });
 });
});


<%end%>

<div class="section">
	<div class="head">
		<h2>出价设置</h2>
	</div>
	<h3>您在同一渠道的发布策略中，您的出价越高，获胜的几率就越大</h3>
	<%= form_for @publish_policy,:as=>:publish_policy,:url=>save_step_3_ad_owner_advertisement_publish_policy_path(@advertisement,@publish_policy,:format=>:html),
	                          :html=>{:class=>'valiable',:method=>:post,:id=>"publish_policy_form"} do |f|%>
	<fieldset>
		<%= f.label :bid_price,:class=>"form-label"%>
		<div class="group">
		<%= f.text_field :bid_price,:class=>"required number",:size=>25,:id=>'base_pri'%>
		<span class="help" id="notice">
			出价不能小于<%= @publish_policy.determine_base_price%>
		</span>
		</div>
	</fieldset>
	<div class="buttons">
		<%= f.submit "提交",:class=>'primary_button'%>
	</div>
	<%end%>
</div>